[package]
name = "mod-sdk"
version = "0.1.0"
authors = []
edition = "2021"
repository = "https://github.com/CronCats/cw-croncat"

[dependencies]
cosmwasm-std = { version = "1.1.9" }
cosmwasm-schema = { version = "=1.1.9" }
thiserror = { version = "1.0" }
