[package]
name = "croncat-sdk-core"
version = "0.1.0"
authors = ["foo"]
edition = "2021"
repository = "https://github.com/CronCats/cw-croncat"

[dependencies]
cosmwasm-schema = { version = "=1.1.9" }
cosmwasm-std = { version = "1.1.9" }
cw20 = { version = "0.16.0" }
