[package]
name = "croncat-factory"
version = "0.1.0"
authors = ["foo"]
edition = "2021"
repository = "https://github.com/CronCats/cw-croncat"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-std = { version = "1.1.9" }
cosmwasm-schema = { version = "=1.1.9" }
thiserror = { version = "1.0" }
cw2 = "1.0.1"
cw-storage-plus = "1.0.1"
cw-utils = "0.16.0"
croncat-sdk-factory = { path = "../../packages/croncat-sdk-factory" }

[dev-dependencies]
cw-multi-test = { version = "0.16.0" }
anyhow = "1"
cw20-base = { version = "0.16.0", features = ["library"] }
cw20 = { version = "0.16.0" }
