[package]
name = "croncat-sdk-manager"
version = "0.1.0"
authors = ["foo"]
edition = "2021"
repository = "https://github.com/CronCats/cw-croncat"

[dependencies]
cosmwasm-std = { version = "1.1.9" }
cosmwasm-schema = { version = "=1.1.9" }
thiserror = { version = "1.0" }
cw20 = { version = "0.16.0" }
croncat-sdk-core = { path = "../croncat-sdk-core" }
