[package]
name = "croncat-integration-utils"
version = "0.1.4"
authors = { workspace = true }
edition = "2021"
repository = "https://github.com/CronCats/cw-croncat"
license = { workspace = true }
description = "Integrate CosmWasm contracts with CronCat automation. Contains smart contract and test helpers."

[dependencies]
thiserror = { workspace = true }
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw20 = { workspace = true }
croncat-sdk-tasks = { workspace = true }
croncat-sdk-manager = { workspace = true }
cw-utils = { workspace = true }
serde-json-wasm = { workspace = true }
cosmwasm-storage = { workspace = true }
serde_json = { workspace = true }
