[package]
name = "croncat-mod-dao"
version = "0.1.0"
authors = []
edition = "2021"
repository = "https://github.com/CronCats/cw-croncat"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-std = { version = "1.1.9" }
cosmwasm-schema = { version = "=1.1.9" }
cw2 = "1.0.1"
mod-sdk = { path = "../../packages/mod-sdk" }
schemars = "0.8.11"
serde = { version = "1.0" }
dao-voting = { version = "2.0.0-beta", git = "https://github.com/DA0-DA0/dao-contracts.git" }
dao-proposal-single = { version = "2.0.0-beta", git = "https://github.com/DA0-DA0/dao-contracts", features = ["library"] }
dao-proposal-multiple = { version = "2.0.0-beta", git = "https://github.com/DA0-DA0/dao-contracts", features = ["library"] }

[dev-dependencies]
cw20 = { version = "0.16.0" }
cw20-base = { version = "0.16.0", features = ["library"] }
cw20-stake = { version = "2.0.0-beta", git = "https://github.com/DA0-DA0/dao-contracts" }
cw-multi-test = { version = "0.16.0" }
cw-utils = "0.16.0"
dao-voting-cw20-staked = { version = "2.0.0-beta", git = "https://github.com/DA0-DA0/dao-contracts" }
dao-core = { version = "2.0.0-beta", git = "https://github.com/DA0-DA0/dao-contracts" }
dao-interface = { version = "2.0.0-beta", git = "https://github.com/DA0-DA0/dao-contracts" }
