# Based on https://github.com/actions-rs/example/blob/master/.github/workflows/quickstart.yml

on: [push, pull_request]

name: Basic

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.66.0
          target: wasm32-unknown-unknown
          override: true

      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          RUST_BACKTRACE: 1

      - name: Compile WASM contract
        run: |
          set -e
          export RUSTFLAGS='-C link-arg=-s'
          EXCLUDED_PACKAGE="croncat_integration_testing"
          
          for PACKAGE in $(cargo metadata --format-version 1 --no-deps | jq '.packages[] | .name' -r)
          do
            if [ "$PACKAGE" != "$EXCLUDED_PACKAGE" ]; then
              echo "Testing package: $PACKAGE"
              cargo test --package "$PACKAGE"
            fi
          done
          
          # Finally build the integration tests
          cargo test --release --lib --manifest-path integration-sdk/croncat-integration-testing/Cargo.toml

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.66.0
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets -- -D warnings
      
      - name: Generate Schema
        run: ./scripts/schema.sh

      - name: Show Schema changes
        run: git status --porcelain

      - name: Schema Changes
        # fails if any changes not committed
        run: test -z "$(git status --porcelain)"
